steps:

# uses https://github.com/afirth/cloud-builders-community/tree/master/helm,
# prefetch docker image to allow parallel deployments
- name: 'gcr.io/cloud-builders/docker'
  id: pull-helm
  args: ['pull', 'gcr.io/$PROJECT_ID/helm:latest']

- name: 'gcr.io/$PROJECT_ID/helm'
  id: external-dns
  # run in parallel
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'external-dns',
    '--debug',
    '--force',
    '--namespace', 'external-dns',
    '-f', './external-dns/values.yaml',
    '--set', 'txtOwnerId=${_CONTAINER_CLUSTER}',
    '--set', 'domainFilters[0]=${_DOMAIN_0}',
    '--set', 'logLevel=debug',
    'stable/external-dns'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
  - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: nginx-ingress
  # run in parallel
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'nginx-ingress',
    '--debug',
    '--force',
    '--namespace', 'nginx-ingress',
    '-f', './nginx-ingress/values.yaml',
    'stable/nginx-ingress'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
  - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: cert-manager
  # run in parallel
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'cert-manager',
    '--debug',
    '--force',
    '--namespace', 'cert-manager',
    '-f', './cert-manager/values.yaml',
    'stable/cert-manager'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
  - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: cert-manager-issuers
  waitFor:
    - cert-manager
  args: [
    'upgrade',
    '--install', 'cert-manager-issuers',
    '--set', 'email=${_EMAIL}',
    '--debug',
    '--force',
    '--namespace', 'cert-manager',
    'https://github.com/afirth/cert-manager-issuers/releases/download/v0.0.2/cert-manager-issuers-v0.0.2.tgz'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
  - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
  - 'TILLERLESS=true'

timeout: 200s
