steps:

# uses https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/helm docker image which must be built in the project
# you can fork and configure a cloudbuild for https://github.com/afirth/cloud-builders-community/blob/master/helm/cloudbuild.yaml

#TODO cert-manager is a CF
#FIXME version changes will break
# see https://github.com/jetstack/cert-manager/pull/1138 and see where it goes
# -AF 2019-01
- name: 'gcr.io/cloud-builders/kubectl'
  id: cert-manager-crds
  waitFor: ['-']
  args: ['apply', '-f', 'https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: cert-manager-namespace
  args: ['apply', '-f', './cert-manager/namespace.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'

- name: 'gcr.io/cloud-builders/kubectl'
  id: prometheus-crds
  args: ['apply', '-f', './prometheus-operator/crd-manifests/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'

# prefetch docker image to allow parallel deployments
- name: 'gcr.io/cloud-builders/docker'
  id: pull-helm
  waitFor: ['-']
  args: ['pull', 'gcr.io/$PROJECT_ID/helm:latest']

- name: 'gcr.io/$PROJECT_ID/helm'
  id: external-dns
  # run in parallel
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'external-dns',
    '--debug',
    '--force',
    '--namespace', 'external-dns',
    '-f', './external-dns/values.yaml',
    '--set', 'txtOwnerId=${_CONTAINER_CLUSTER}',
    '--set', 'domainFilters[0]=${_DOMAIN_0}',
    '--set', 'logLevel=debug',
    'stable/external-dns'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: nginx-ingress
  # run in parallel
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'nginx-ingress',
    '--debug',
    '--force',
    '--namespace', 'nginx-ingress',
    '-f', './nginx-ingress/values.yaml',
    'stable/nginx-ingress'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: cert-manager
  # run in parallel
  waitFor:
    - cert-manager-crds
    - cert-manager-namespace
    - pull-helm
  args: [
    'upgrade',
    '--install', 'cert-manager',
    '--debug',
    '--force',
    '--namespace', 'cert-manager',
    '-f', './cert-manager/values.yaml',
    'stable/cert-manager'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: cert-manager-issuers
  waitFor:
    - cert-manager
  args: [
    'upgrade',
    '--install', 'cert-manager-issuers',
    '--set', 'email=${_EMAIL}',
    '--debug',
    '--force',
    '--namespace', 'cert-manager',
    'https://github.com/afirth/cert-manager-issuers/releases/download/v0.0.4/cert-manager-issuers-v0.0.4.tgz'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: prometheus-operator
  waitFor:
    - pull-helm
    - prometheus-crds
  args: [
    'upgrade',
    '--install', 'prometheus-operator',
    '--force',
    '--namespace', 'prometheus-operator',
    '-f', './prometheus-operator/values.yaml',
    'stable/prometheus-operator'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: nfs
  waitFor:
    - pull-helm
  args: [
    'upgrade',
    '--install', 'nfs',
    '--debug',
    '--force',
    '--namespace', 'nfs',
    '--set', 'persistence.enabled=true,persistence.size=1Gi',
    'stable/nfs-server-provisioner'
    ]
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'

- name: 'gcr.io/$PROJECT_ID/helm'
  id: wordpress
  # run in parallel
  waitFor:
    - pull-helm
    - nfs
  entrypoint: 'bash'
  args: [ '-c', './wordpress/helm-install.sh' ]
  env:
    - 'HOSTNAME=wp.${_DOMAIN_0}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'TILLER_NAMESPACE=${_TILLER_NAMESPACE}'
    - 'TILLERLESS=true'
  secretEnv:
    - 'WP_PASSWORD'
    - 'MARIADB_ROOT_PASSWORD'
    - 'MARIADB_USER_PASSWORD'

timeout: 200s

secrets:
# - kmsKeyName: projects/${PROJECT_ID}/locations/global/keyRings/${PROJECT_ID}/cryptoKeys/cloudbuild
- kmsKeyName: projects/flying-blue-mantis/locations/global/keyRings/flying-blue-mantis/cryptoKeys/cloudbuild
  secretEnv:
    WP_PASSWORD: CiQA7J4wCRIeBM6Q67ofYRHZtnr2y/i45D2HVkpzkfWCRwA5S7ASNQCQvfKNCpE8Fo9ti7uDZZeVeMG/Rm71zmyuHAg8ceQTOyE+RbjO8O3zrLrT+Sfs7QZAWOfV
    MARIADB_ROOT_PASSWORD: CiQA7J4wCftJpKSiT03vlQcrQMSDC/TAd1Z+NuXMDnmErWzkqxYSQQCQvfKNf58Xt0wQdHPfhcAeDc5+45N+cGfSsXYkJudtCODc2D9BGnwMIRWZvx4IBKD8jCOzpqIbHP0UJqmwTb6X
    MARIADB_USER_PASSWORD: CiQA7J4wCWGJJcABbGicXF+JzV2JdzV2goxoZOxx3LB36ucBrsMSNgCQvfKN2DrC57Jzb9BEP9OORvTDcl5qEVjm9swS48yrVEq2fZ3ExL4WAf5BLF/wSWZAvr5zMA==
