alertmanager:
  
  alertmanagerSpec:
    
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    resources:
     requests:
       memory: 100Mi

grafana:
  ## this will be randomized by the grafana chart - AF
  adminPassword: ""

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: true

kubeEtcd:
  enabled: false

prometheusOperator:

  resources:
   limits:
     cpu: 200m
     memory: 200Mi
   requests:
     cpu: 50m
     memory: 50Mi

prometheus:
  
  prometheusSpec:

    resources:
     requests:
       memory: 100Mi
       cpu: 50m

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
