controller:
  name: controller
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.21.0"

  ##  we are running daemonset with no loadbalancer (dns load balancing) for $ reasons
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  ## Use host ports 80 and 443
  daemonset:
    useHostPort: true

    hostPorts:
      http: 80
      https: 443

  ## DaemonSet or Deployment
  ##
  kind: DaemonSet

  # The update strategy to apply to the Deployment or DaemonSet
  ##
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate


  resources:
  #really don't want to kill the ingress controllers...
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  service:
    enableHttp: true
    enableHttps: true

    ## Set external traffic policy to: "Local" to preserve source IP on
    ## providers supporting it
    ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
    externalTrafficPolicy: "Local"

    healthCheckNodePort: 0

    targetPorts:
      http: http
      https: https

    type: NodePort

    # type: NodePort
    # nodePorts:
    #   http: 32080
    #   https: 32443
    nodePorts:
      http: ""
      https: ""


  ## If controller.stats.enabled = true and controller.metrics.enabled = true, Prometheus metrics will be exported
  stats:
    enabled: false
  metrics:
    enabled: false


## Default 404 backend
defaultBackend:
  resources:
   limits:
     cpu: 10m
     memory: 20Mi
   requests:
     cpu: 10m
     memory: 20Mi
