### OVERRIDDEN by cloudbuild.yaml

# When using the TXT registry, a name that identifies this instance of ExternalDNS
txtOwnerId: ""
## Limit possible target zones by domain suffixes (optional)
domainFilters: []
# Verbosity of the logs (options: panic, debug, info, warn, error, fatal)
logLevel: info

### END OVERRIDES by cloudbuild.yaml

## This controls which types of resource external-dns should 'watch' for new
## DNS entries.
sources:
  - ingress

# Allow external-dns to publish DNS records for ClusterIP services (optional)
publishInternalServices: false

provider: google

# Registry to use for ownership (txt or noop)
registry: "txt"

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: upsert-only

## CPU and Memory limit and request for external-dns
resources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 10Mi

rbac:
  ## If true, create & use RBAC resources
  ##
  create: true
  # Beginning with Kubernetes 1.8, the api is stable and v1 can be used.
  apiVersion: v1
